### PR TITLE
Fixing login/register button position

### PR DESCRIPTION
**Pull request by irfanfath123**

### CODE REVIEW

**Review by abay-2002 — COMMENTED** [review]
have you tested it on your local dev???

**Comment by irfanfath123** [comment]
> have you tested it on your local dev???

yes, nassami I have test in my local dev

**Comment by abay-2002** [comment]
> > have you tested it on your local dev???
> 
> yes, nassami I have test in my local dev

english plis, rong!! mdedee

**Review by abay-2002 — APPROVED** [review]
iye'

**Comment by abay-2002** [comment]
ijo2 tawwa

**Pull request merged**
