### PR TITLE
Update News.tsx guys

### PR DESCRIPTION
**Pull request by wiryorudolf**
Please check this out bruh. there is some update of this project on Layout. have a nice day and thank you.

### CODE REVIEW

**Review by abay-2002 — APPROVED** [review]
aight m8

**Comment by abay-2002** [comment]
Fix your branch bruh smh @wiryorudolf

**Comment by wiryorudolf** [comment]
what wrong bruh... I already pull request from main branch on my repo to your components branch

**Comment by wiryorudolf** [comment]
should i do pull request from my component branch too?

**Comment by wiryorudolf** [comment]
maybe there is some bug on this app

**Comment by abay-2002** [comment]
leme check

**Review by abay-2002 — APPROVED** [review]
a8, next time try a smaller file size m8

**Pull request merged**
